name: RAG API CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        env:               # 👈 inject secrets into test environment
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          HF_API_KEY: ${{ secrets.HF_API_KEY }}
          DB_URL: ${{ secrets.DB_URL }}
        run: pytest -q || echo "No tests yet"

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image
        env:               # 👈 inject secrets into docker build
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          HF_API_KEY: ${{ secrets.HF_API_KEY }}
          DB_URL: ${{ secrets.DB_URL }}
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/rag-api:latest -f ops/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rag-api:latest


